#!/usr/bin/env bash
# setup_group.sh — one-time (per group) setup of the forum-group notification hub.
#
# Prereqs (manual, done by Alex in the Telegram app):
#   1. Create a new group (e.g. "AO Personal OS"), just you + @ao_personal_os_bot.
#   2. Group Settings → Topics → enable.
#   3. Promote the bot to Admin with at least "Manage Topics".
#   4. Send any message in the group (so it shows up in getUpdates).
#
# What this script does:
#   - Finds the forum group via getUpdates (most recent forum-supergroup seen).
#   - Stores its chat id in Keychain as TELEGRAM_GROUP_CHAT_ID.
#   - Creates the standard topics via createForumTopic (skips ones already in
#     topics.env — Bot API has no "list topics", so topics.env is the ledger).
#   - Writes/updates topics.env next to this script (committed; ids aren't secrets).
#
# Re-runnable: existing topics.env entries are kept, missing ones created.
# On a SECOND machine, only the Keychain step is needed:
#   security add-generic-password -U -a "$USER" -s TELEGRAM_GROUP_CHAT_ID -w '<chat_id>'
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"

TOKEN="$(security find-generic-password -a "$USER" -s TELEGRAM_BOT_TOKEN -w 2>/dev/null || echo "${TELEGRAM_BOT_TOKEN:-}")"
[ -n "$TOKEN" ] || { echo "[setup_group] no bot token — run setup.sh first" >&2; exit 1; }
API="https://api.telegram.org/bot${TOKEN}"

command -v jq >/dev/null 2>&1 || { echo "[setup_group] jq not installed (brew install jq)" >&2; exit 1; }

# --- 1. Find the forum group -------------------------------------------------
# Allow override: setup_group.sh <chat_id> skips discovery.
if [ "$#" -ge 1 ]; then
  GROUP_ID="$1"
else
  updates="$(curl -fsS --max-time 20 "$API/getUpdates?limit=100")"
  GROUP_ID="$(jq -r '
    [.result[]
     | (.message // .my_chat_member // empty)
     | .chat
     | select(.type == "supergroup" and .is_forum == true)
     | .id] | last // empty' <<<"$updates")"
  if [ -z "$GROUP_ID" ]; then
    echo "[setup_group] no forum group found in getUpdates." >&2
    echo "  → Make sure Topics are ENABLED, the bot is in the group," >&2
    echo "    and you sent a fresh message in the group, then re-run." >&2
    exit 1
  fi
fi

title="$(curl -fsS --max-time 20 "$API/getChat?chat_id=${GROUP_ID}" | jq -r '.result.title // "?"')"
echo "[setup_group] using group: $title ($GROUP_ID)"

# --- 2. Verify bot can manage topics -----------------------------------------
bot_id="$(curl -fsS --max-time 20 "$API/getMe" | jq -r '.result.id')"
member="$(curl -fsS --max-time 20 "$API/getChatMember?chat_id=${GROUP_ID}&user_id=${bot_id}")"
can_manage="$(jq -r '.result | (.status == "creator") or (.can_manage_topics == true)' <<<"$member")"
if [ "$can_manage" != "true" ]; then
  echo "[setup_group] bot is not an admin with 'Manage Topics' in $title." >&2
  echo "  → Promote it (group → Administrators → bot → Manage Topics), then re-run." >&2
  exit 1
fi

# --- 3. Store group id in Keychain --------------------------------------------
security add-generic-password -U -a "$USER" -s TELEGRAM_GROUP_CHAT_ID -w "$GROUP_ID"
echo "[setup_group] TELEGRAM_GROUP_CHAT_ID stored in Keychain"

# --- 4. Create topics (idempotent via topics.env ledger) ----------------------
TOPICS_ENV="$HERE/topics.env"
# shellcheck source=/dev/null
[ -f "$TOPICS_ENV" ] && source "$TOPICS_ENV"

# slug|display name|icon_color (Telegram's fixed palette)
# NOTE: "goals-tasks" (🎯) and "insights" (💡) were deleted 2026-06-12 — goal/task/
# insight captures now land in Alex's pinned Apple Notes via apple-notes-sync.
TOPIC_DEFS=(
  "english-coaching|🎓 English Coaching|7322096"
  "inbox-drafts|📨 Inbox & Drafts|16766590"
  "daily-digest|📰 Daily Digest|13338331"
  "books|📚 Books|9367192"
  "dropzone|📥 Drop Zone|16749490"
  "explore|🔭 Articles & Topics|7322096"
)

declare -a lines=()
for def in "${TOPIC_DEFS[@]}"; do
  slug="${def%%|*}"; rest="${def#*|}"; name="${rest%%|*}"; color="${rest##*|}"
  key="TG_TOPIC_$(printf '%s' "$slug" | tr 'a-z-' 'A-Z_')"
  existing="${!key:-}"
  if [ -n "$existing" ]; then
    echo "[setup_group] topic '$name' already known (thread $existing) — keeping"
    lines+=("$key=$existing")
    continue
  fi
  resp="$(curl -fsS --max-time 20 -X POST "$API/createForumTopic" \
    --data-urlencode "chat_id=${GROUP_ID}" \
    --data-urlencode "name=${name}" \
    --data-urlencode "icon_color=${color}")"
  tid="$(jq -r '.result.message_thread_id // empty' <<<"$resp")"
  if [ -z "$tid" ]; then
    echo "[setup_group] FAILED to create topic '$name': $resp" >&2
    exit 1
  fi
  echo "[setup_group] created topic '$name' → thread $tid"
  lines+=("$key=$tid")
done

{
  echo "# topics.env — TG_TOPIC slug → message_thread_id map for the forum group."
  echo "# Generated by setup_group.sh ($title). Committed: thread ids aren't secrets."
  echo "# The group chat id itself lives in Keychain (TELEGRAM_GROUP_CHAT_ID)."
  for l in "${lines[@]}"; do echo "$l"; done
} >"$TOPICS_ENV"
echo "[setup_group] wrote $TOPICS_ENV"

# --- 5. Smoke test ------------------------------------------------------------
for def in "${TOPIC_DEFS[@]}"; do
  slug="${def%%|*}"
  echo "🔧 topic wiring test ($slug)" | TG_TOPIC="$slug" "$HERE/telegram_send.sh" \
    && echo "[setup_group] smoke OK: $slug" \
    || echo "[setup_group] smoke FAILED: $slug" >&2
done
echo "✅ Telegram notification hub configured" | "$HERE/telegram_send.sh"
echo "[setup_group] done"
