#!/usr/bin/env bash
# setup.sh — idempotent one-time setup for the Clockify panel.
#   * stores the Clockify API key in macOS Keychain (if passed / present)
#   * validates the key against GET /user
#   * normalises the four project colors (violet/red/blue/green)
#   * creates .work/
#   * installs + loads the launchd "always-on at login" agent
#
# Usage:
#   ./setup.sh                 # use the key already in Keychain
#   ./setup.sh <CLOCKIFY_KEY>  # store this key in Keychain first
set -euo pipefail
cd "$(dirname "$0")"

# --- 1. store key in Keychain if provided as $1 -----------------------------
if [ "${1:-}" != "" ]; then
  echo "Storing Clockify API key in Keychain (service CLOCKIFY_API_KEY)…"
  security add-generic-password -U -a "$USER" -s CLOCKIFY_API_KEY -w "$1"
fi

# shellcheck disable=SC1091
source ./config.sh

if [ -z "${CLOCKIFY_API_KEY:-}" ]; then
  echo "ERROR: no Clockify API key. Run: ./setup.sh <YOUR_API_KEY>" >&2
  exit 1
fi

# --- 2. validate + fetch identity ------------------------------------------
echo "Validating key against Clockify…"
USER_JSON="$(curl -fsS -H "X-Api-Key: $CLOCKIFY_API_KEY" https://api.clockify.me/api/v1/user)" \
  || { echo "ERROR: key rejected by Clockify (GET /user failed)." >&2; exit 1; }

WS="$("$PYTHON_BIN" -c 'import sys,json;u=json.load(sys.stdin);print(u.get("activeWorkspace") or u.get("defaultWorkspace"))' <<<"$USER_JSON")"
echo "  OK — workspace $WS"

# --- 3. normalise the four project colors ----------------------------------
# key -> target hex (violet / red / blue / green). GC is already red but we set
# it anyway for idempotency. Matching is by exact project name.
echo "Applying project colors (SS violet, GC red, JS blue, EF green)…"
# Non-fatal: editing a project requires workspace-admin rights, which a plain
# personal API key may lack (HTTP 403). If so we warn and move on — the app
# just uses whatever colors Clockify reports. Change them in the Clockify web
# UI (Projects → ⋯ → Edit) and the buttons follow.
"$PYTHON_BIN" - "$CLOCKIFY_API_KEY" "$WS" <<'PY' || echo "  (color step skipped — see warning above)"
import json, sys, urllib.request, urllib.error
key, ws = sys.argv[1], sys.argv[2]
BASE = "https://api.clockify.me/api/v1"
TARGET = {"SS": "#7E57C2", "GC": "#F44336", "JS": "#2196F3", "EF": "#4CAF50"}

def req(method, path, body=None):
    data = json.dumps(body).encode() if body is not None else None
    h = {"X-Api-Key": key}
    if data: h["Content-Type"] = "application/json"
    r = urllib.request.Request(BASE + path, data=data, headers=h, method=method)
    with urllib.request.urlopen(r, timeout=20) as resp:
        raw = resp.read()
        return json.loads(raw) if raw else None

projects = req("GET", f"/workspaces/{ws}/projects?page-size=200&archived=false")
by_name = {p["name"]: p for p in projects}
for k, color in TARGET.items():
    p = by_name.get(k)
    if not p:
        print(f"  ! project '{k}' not found — skipping"); continue
    if (p.get("color") or "").upper() == color.upper():
        print(f"  = {k} already {color}"); continue
    try:
        req("PUT", f"/workspaces/{ws}/projects/{p['id']}", {"name": p["name"], "color": color})
        print(f"  -> {k} set to {color}")
    except urllib.error.HTTPError as e:
        if e.code == 403:
            print(f"  ! {k}: no permission to edit project color via API (403) — "
                  "change it in the Clockify web UI; the button will follow.")
        else:
            print(f"  ! {k}: color update failed (HTTP {e.code})")

after = {p["name"]: p.get("color") for p in req("GET", f"/workspaces/{ws}/projects?page-size=200&archived=false")}
print("  current colors:", {k: after.get(k) for k in TARGET})
PY

# --- 4. .work/ --------------------------------------------------------------
mkdir -p "$WORK"

# --- 5. install a runtime copy outside ~/Documents -------------------------
# ~/Documents is TCC-protected: a launchd agent's /bin/bash can't exec scripts
# there without a manual Full Disk Access grant. ~/Library is not protected, so
# we run the agent from an installed copy there. The repo stays the source of
# truth; re-run setup.sh after editing server.py / index.html to redeploy.
INSTALL_DIR="$HOME/Library/Application Support/clockify-panel"
echo "Installing runtime copy to $INSTALL_DIR …"
mkdir -p "$INSTALL_DIR"
cp "$PANEL_DIR/server.py" "$PANEL_DIR/index.html" "$INSTALL_DIR/"
xattr -c "$INSTALL_DIR/server.py" "$INSTALL_DIR/index.html" 2>/dev/null || true
cat > "$INSTALL_DIR/launch.sh" <<EOF
#!/usr/bin/env bash
# Generated by setup.sh — launched by the launchd agent.
DIR="\$(cd "\$(dirname "\$0")" && pwd)"
export PORT="\${PORT:-$PORT}"
export CLOCKIFY_API_KEY="\$(security find-generic-password -a "\$USER" -s CLOCKIFY_API_KEY -w 2>/dev/null)"
exec "$PYTHON_BIN" "\$DIR/server.py"
EOF
chmod +x "$INSTALL_DIR/launch.sh"

# --- 6. launchd agent (always-on at login) ---------------------------------
PLIST_SRC="$PANEL_DIR/com.user.clockify-panel.plist"
PLIST_DST="$HOME/Library/LaunchAgents/com.user.clockify-panel.plist"
if [ -f "$PLIST_SRC" ]; then
  echo "Installing launchd agent…"
  mkdir -p "$HOME/Library/LaunchAgents"
  cp "$PLIST_SRC" "$PLIST_DST"
  # free the port if something is already bound, then (re)load
  lsof -ti tcp:"$PORT" | xargs kill -9 2>/dev/null || true
  launchctl unload "$PLIST_DST" 2>/dev/null || true
  launchctl load "$PLIST_DST"
  echo "  loaded — panel will auto-start at login."
fi

echo ""
echo "Done. Open  http://localhost:$PORT"
echo "Run manually with: ./run.sh"
